[package]
name = "vmm"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
base-62 = "0.1.1"
clap = { version = "4.5", features = ["derive"] }
directories = "6.0.0"
futures = "0.3.31"
rand_core = { version = "0.9", features = ["os_rng"] }
rtnetlink = { version = "0.17", features = ["smol_socket"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tun = "0.8.0"
